"""Chat service for the investment advisor."""

from langchain_groq import ChatGroq

from app.config import settings
from app.services.mongodb_service import (
    create_chat_conversation,
    get_chat_conversation,
    save_chat_message,
    update_chat_title,
)


llm = ChatGroq(
    model=settings.groq_model,
    temperature=0
)


def generate_chat_response(
    user_id: str,
    message: str,
    conversation_id: str | None = None,
    investment_goal: str | None = None,
    investment_amount: float | None = None,
    duration_years: int | None = None,
    risk_profile: str | None = None,
    portfolio: dict | None = None,
) -> tuple[str, str]:

    # Create a conversation if this is the first message.
    if not conversation_id:
        conversation_id = create_chat_conversation(user_id)

        if not conversation_id:
            raise RuntimeError("Unable to create chat conversation")

    # Retrieve existing conversation.
    conversation = get_chat_conversation(
        conversation_id,
        user_id
    )

    if not conversation:
        raise ValueError("Conversation not found")

    previous_messages = conversation.get("messages", [])

    history_text = ""

    for item in previous_messages[-10:]:
        role = item.get("role", "user")
        content = item.get("content", "")

        history_text += f"{role.upper()}: {content}\n"

    portfolio_text = "No portfolio has been generated yet."

    if portfolio:
        portfolio_text = "\n".join(
            f"- {asset}: ₹{amount:,.2f}"
            for asset, amount in portfolio.items()
        )

    prompt = f"""
You are the conversational AI assistant for an investment advisory application.

Your job is to answer questions about the user's investment portfolio,
investment strategy, risk profile, and the analysis generated by the system.

IMPORTANT:
- Use the supplied portfolio context when answering.
- Do not invent portfolio holdings or financial data.
- Do not claim that an action was performed unless the system actually performed it.
- Give clear explanations in simple language.
- If the user asks why an asset was recommended, explain using the
  available portfolio context.
- For now, do NOT regenerate the portfolio yourself.
- Portfolio-changing requests will be handled by a later workflow.

CURRENT INVESTMENT CONTEXT

Goal:
{investment_goal or "Not provided"}

Investment amount:
{investment_amount if investment_amount is not None else "Not provided"}

Investment horizon:
{duration_years if duration_years is not None else "Not provided"} years

Risk profile:
{risk_profile or "Not provided"}

Current portfolio:
{portfolio_text}


PREVIOUS CONVERSATION

{history_text or "No previous messages."}


USER'S NEW MESSAGE

{message}

Answer the user's message directly.
"""

    response = llm.invoke(prompt)

    assistant_message = response.content

    # Save user message.
    save_chat_message(
        conversation_id=conversation_id,
        user_id=user_id,
        role="user",
        content=message
    )

    # Save assistant response.
    save_chat_message(
        conversation_id=conversation_id,
        user_id=user_id,
        role="assistant",
        content=assistant_message
    )

    # Give the conversation a useful title after the first message.
    if not previous_messages:
        title = message[:60].strip()

        if len(message) > 60:
            title += "..."

        update_chat_title(
            conversation_id,
            user_id,
            title
        )

    return assistant_message, conversation_id